# Generated by Django 2.0.4 on 2018-05-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('realname', models.CharField(max_length=50)),
                ('last_login_time', models.CharField(max_length=50)),
                ('last_login_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
