# Generated by Django 2.0.4 on 2018-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_login_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_login_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
