# Generated by Django 2.0.4 on 2018-05-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admin_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
