# Generated by Django 2.0.4 on 2018-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_classroom_porttype_subjectdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porttype',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='porttype',
            name='rname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
