# Generated by Django 2.0.4 on 2018-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180508_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetail',
            name='subject_teacher_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
