# Generated by Django 2.0.4 on 2018-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_subjectdetail_subject_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_number',
            field=models.CharField(max_length=10),
        ),
    ]
