# Generated by Django 2.0.4 on 2018-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_estimatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatehistory',
            name='is_stop',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
