# Generated by Django 2.0.4 on 2018-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_estimatehistory_is_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatehistory',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
