# Generated by Django 2.0.4 on 2018-05-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_estimatehistory_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatehistory',
            name='is_stop',
            field=models.BooleanField(default=False),
        ),
    ]
