# Generated by Django 2.0.5 on 2018-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20180516_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=0)),
                ('location_name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
