# Generated by Django 2.0.5 on 2018-05-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_frontendshow_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendshow',
            name='location',
        ),
    ]
