# Generated by Django 2.0.5 on 2018-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_frontendshow_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendshow',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
