# Generated by Django 2.0.5 on 2018-05-30 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_frontendshow_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendshow',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login.Location'),
        ),
    ]
